docker run -it --gpus all \
  -e DISPLAY \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -v /home/rini-debian/git-stash/lvgl-ui-detector/lvgl_ui_generator_v2/lv_micropython/ports/unix/build-standard/micropython:/opt/micropython \
  -v /home/rini-debian/git-stash/lvgl-ui-detector/lvgl_ui_generator_v2/src:/main/ \
  -e MICROPYTHON_BIN=/opt/micropython \
  -e MICROPYTHON_MAIN=/main/main.py \
  -v /tmp/ssh-XXXXXXAfqLtw/agent.52685:/tmp/ssh-XXXXXXAfqLtw/agent.52685 \
  -e SSH_AUTH_SOCK=/tmp/ssh-XXXXXXAfqLtw/agent.52685 \
  -l clearml-worker-id=local-dev:0 \
  -l clearml-parent-worker-id=local-dev:0 \
  -e CLEARML_WORKER_ID=local-dev:0 \
  -e CLEARML_DOCKER_IMAGE=nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04 \
  -e CLEARML_TASK_ID=647356cfc4ce474f831589b0a9ede253 \
  -v /home/rini-debian/.gitconfig:/root/.gitconfig \
  -v /home/rini-debian/clearml.conf:/tmp/clearml.conf \
  -e CLEARML_CONFIG_FILE=/tmp/clearml.conf \
  -v /home/rini-debian/.clearml/apt-cache:/var/cache/apt/archives \
  -v /home/rini-debian/.clearml/pip-cache:/root/.cache/pip \
  -v /home/rini-debian/.clearml/poetry-cache:/root/.cache/pypoetry \
  -v /home/rini-debian/.clearml/pip-download-cache:/root/.clearml/pip-download-cache \
  -v /home/rini-debian/.clearml/cache:/clearml_agent_cache \
  -v /home/rini-debian/.clearml/vcs-cache:/root/.clearml/vcs-cache \
  -v /home/rini-debian/.clearml/venvs-cache:/root/.clearml/venvs-cache \
  --rm nvidia/cuda:12.3.2-cudnn9-runtime-ubuntu22.04 bash -c 'echo \'Binary::apt::APT::Keep-Downloaded-Packages "true";\' > /etc/apt/apt.conf.d/docker-clean ; chown -R root /root/.cache/pip ; export DEBIAN_FRONTEND=noninteractive ; export CLEARML_APT_INSTALL="$CLEARML_APT_INSTALL libsm6 libxext6 libxrender-dev libglib2.0-0" ; [ ! -z $(which git) ] || export CLEARML_APT_INSTALL="$CLEARML_APT_INSTALL git" ; declare LOCAL_PYTHON ; [ ! -z $LOCAL_PYTHON ] || for i in {15..5}; do which python3.$i && python3.$i -m pip --version && export LOCAL_PYTHON=$(which python3.$i) && break ; done ; [ ! -z $LOCAL_PYTHON ] || export CLEARML_APT_INSTALL="$CLEARML_APT_INSTALL python3-pip" ; [ -z "$CLEARML_APT_INSTALL" ] || (apt-get update -y ; apt-get install -y $CLEARML_APT_INSTALL) ; [ ! -z $LOCAL_PYTHON ] || export LOCAL_PYTHON=python3 ; $LOCAL_PYTHON -m pip install --break-system-packages -U "pip<20.2 ; python_version < 3.10" "pip<22.3 ; python_version >= 3.10" ; $LOCAL_PYTHON -m pip install --break-system-packages -U clearml-agent ; [ -d /root/.ssh ] || mkdir -p /root/.ssh ; ssh-keyscan github.com >> /root/.ssh/known_hosts ; cp /tmp/clearml.conf ~/default_clearml.conf ; NVIDIA_VISIBLE_DEVICES=all $LOCAL_PYTHON -u -m clearml_agent execute --disable-monitoring  --id "647356cfc4ce474f831589b0a9ede253"; bash;''
